services:
  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    ports:
      - "5005:5005"
    depends_on:
      - "postgres"
    env_file: .env

  postgres:
    image: postgres:16.2
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data/
      - ./database/schemas.sql:/docker-entrypoint-initdb.d/init.sql
    env_file: .env

  pgadmin:
    image: dpage/pgadmin4:latest
    ports:
      - "5050:80"  # Access pgAdmin on http://localhost:5050
    depends_on:
      - postgres
    env_file: .env

volumes:
  postgres-data: