-- W1 foundation: Campus, Editais, Ofertas, DistribuicaoCotas, slim Cursos catalog.

CREATE TYPE METODO_SELECAO AS ENUM('ALEATORIO', 'MERITO', 'HIBRIDO');
CREATE TYPE MERITO_TIPO AS ENUM(
    'HISTORICO_ESCOLAR',
    'NOTA_ENEM',
    'PROVA_ESPECIFICA'
);
CREATE TYPE TERMOS_MODO AS ENUM('PDF', 'URL', 'TEXTO');
CREATE TYPE TURNO AS ENUM('MATUTINO', 'VESPERTINO', 'NOTURNO', 'INTEGRAL');

CREATE TABLE "Campus"(
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "nome" VARCHAR(255) NOT NULL,
    CONSTRAINT "campus_nome_unique" UNIQUE ("nome")
);

CREATE TABLE "Editais"(
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "numero_ano" VARCHAR(255) NOT NULL,
    "metodo_selecao" METODO_SELECAO NOT NULL,
    "merito_tipo" MERITO_TIPO NULL,
    "is_simplificado" BOOLEAN NOT NULL DEFAULT FALSE,
    "fallback_ac_para_rv" BOOLEAN NOT NULL DEFAULT FALSE,
    "termos_modo" TERMOS_MODO NOT NULL,
    "termos_valor" VARCHAR(2048) NOT NULL,
    "link_oficial" VARCHAR(512) NULL,
    "publicado" BOOLEAN NOT NULL DEFAULT FALSE,
    "inscricoes_abertas" BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE "EditalArquivos"(
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "id_edital" BIGINT NOT NULL,
    "arquivo" BYTEA NOT NULL,
    "criado_em" TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE "Cursos"(
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "nome" VARCHAR(255) NOT NULL,
    "eixo_tecnologico" VARCHAR(255) NULL,
    "requisito_escolaridade" VARCHAR(255) NULL,
    "area_conhecimento" VARCHAR(255) NULL
);

CREATE TABLE "Ofertas"(
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "id_edital" BIGINT NOT NULL,
    "id_curso" BIGINT NOT NULL,
    "id_campus" BIGINT NOT NULL,
    "turno" TURNO NOT NULL,
    "vagas_totais" SMALLINT NOT NULL,
    CONSTRAINT "ofertas_edital_curso_campus_turno_unique"
        UNIQUE ("id_edital", "id_curso", "id_campus", "turno")
);

CREATE TABLE "DistribuicaoCotas"(
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "id_oferta" BIGINT NOT NULL,
    "tipo_cota" VARCHAR(50) NOT NULL,
    "vagas" SMALLINT NULL,
    "percentual" DECIMAL(5, 2) NULL,
    CONSTRAINT "distribuicao_cotas_vagas_ou_percentual_chk"
        CHECK ("vagas" IS NOT NULL OR "percentual" IS NOT NULL)
);

CREATE TABLE "Usuarios"(
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "nome_completo" VARCHAR(255) NOT NULL,
    "email" VARCHAR(255) NOT NULL,
    "CPF" VARCHAR(255) NOT NULL,
    "data_nascimento" DATE NOT NULL,
    "telefone" VARCHAR(255) NOT NULL,
    "nome_RG" VARCHAR(255) NOT NULL,
    "RG" BYTEA NOT NULL,
    "nome_historico_escolar" VARCHAR(255) NOT NULL,
    "historico_escolar" BYTEA NOT NULL,
    "renda_familiar" DECIMAL(8, 2) NOT NULL,
    "foto_alt" VARCHAR(255) NOT NULL,
    "foto" BYTEA NOT NULL,
    "ppi" VARCHAR(255) NULL,
    "pcd" BOOLEAN NOT NULL,
    "criado_em" TIMESTAMP NOT NULL,
    "atualizado_em" TIMESTAMP NOT NULL,
    "token" VARCHAR(255) NOT NULL
);
CREATE TABLE "Enderecos"(
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "id_usuario" BIGINT NOT NULL,
    "estado" VARCHAR(255) NOT NULL,
    "cidade" VARCHAR(255) NOT NULL,
    "CEP" VARCHAR(255) NOT NULL,
    "logradouro" VARCHAR(255) NOT NULL,
    "bairro" VARCHAR(255) NOT NULL,
    "numero_residencia" VARCHAR(255) NOT NULL,
    "complemento" VARCHAR(255) NULL
);
CREATE TYPE STATUS_CANDIDATURA AS ENUM(
        'inscricao_recebida',
        'pre_selecionado',
        'analise_documental',
        'aprovado',
        'reprovado',
        'cancelada',
        'desclassificada'
    );
CREATE TYPE TIPO_INGRESSO AS ENUM(
        'sisu',
        'sorteio',
        'ordem_chegada',
        'analise_curricular',
        'transferencia'
    );
CREATE TYPE TIPO_VAGA AS ENUM(
        'AC',
        'PPI',
        'PCD',
        'ESCOLA_PUBLICA',
        'BAIXA_RENDA'
    );
CREATE TABLE "Candidaturas"(
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "id_usuario" BIGINT NOT NULL,
    "id_oferta" BIGINT NOT NULL,
    "id_edital" BIGINT NOT NULL,
    "data_inscricao" DATE NOT NULL,
    "status" STATUS_CANDIDATURA NOT NULL DEFAULT 'inscricao_recebida',
    "tipo_ingresso" TIPO_INGRESSO NULL,
    "tipo_vaga" TIPO_VAGA NOT NULL DEFAULT 'AC',
    "protocolo" VARCHAR(255) NULL
);
CREATE TABLE "Documentos"(
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "id_candidatura" BIGINT NOT NULL,
    "tipo_documento" VARCHAR(255) NOT NULL,
    "nome_arquivo" VARCHAR(255) NOT NULL,
    "arquivo" BYTEA NOT NULL,
    "status_documento" VARCHAR(255) NOT NULL DEFAULT 'em_analise',
    "criado_em" TIMESTAMP NOT NULL
);
CREATE TYPE ETAPA_PROCESSO AS ENUM(
        'periodo_inscricoes',
        'manifestacao_interesse',
        'entrega_documental',
        'analise_documental',
        'publicacao_resultado_preliminar',
        'apresentacao_recurso',
        'analise_recurso',
        'publicacao_resultado_final',
        'matricula',
        'encerrado'
    );
CREATE TYPE RESULTADO_ETAPA AS ENUM('aprovado', 'reprovado', 'pendente');
CREATE TABLE "Etapas Processo"(
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "id_candidatura" BIGINT NOT NULL,
    "id_gestor" BIGINT NOT NULL,
    "tipo_etapa" ETAPA_PROCESSO NOT NULL DEFAULT 'periodo_inscricoes',
    "status" RESULTADO_ETAPA NOT NULL DEFAULT 'pendente',
    "pontuacao" DECIMAL(8, 2) NULL,
    "observacoes" VARCHAR(255) NOT NULL,
    "data_realizacao" DATE NOT NULL,
    "prazo" DATE NOT NULL
);
CREATE TABLE "Gestores"(
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "id_usuario" BIGINT NOT NULL,
    "funcao" VARCHAR(255) NULL
);
CREATE TYPE STATUS_RECURSO AS ENUM(
        'aberto',
        'em_analise',
        'deferido',
        'indeferido'
    );
CREATE TABLE "Recursos"(
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "id_etapa_processo" BIGINT NOT NULL,
    "data_solicitacao" DATE NOT NULL,
    "titulo" VARCHAR(255) NOT NULL,
    "nome_anexo" VARCHAR(255) NOT NULL,
    "arquivo_anexo" BYTEA NOT NULL,
    "status" STATUS_RECURSO NOT NULL DEFAULT 'aberto',
    "id_gestor" BIGINT NOT NULL,
    "observacoes" VARCHAR(255) NOT NULL
);

ALTER TABLE
    "EditalArquivos" ADD CONSTRAINT "edital_arquivos_id_edital_foreign"
    FOREIGN KEY("id_edital") REFERENCES "Editais"("id");
ALTER TABLE
    "Ofertas" ADD CONSTRAINT "ofertas_id_edital_foreign"
    FOREIGN KEY("id_edital") REFERENCES "Editais"("id");
ALTER TABLE
    "Ofertas" ADD CONSTRAINT "ofertas_id_curso_foreign"
    FOREIGN KEY("id_curso") REFERENCES "Cursos"("id");
ALTER TABLE
    "Ofertas" ADD CONSTRAINT "ofertas_id_campus_foreign"
    FOREIGN KEY("id_campus") REFERENCES "Campus"("id");
ALTER TABLE
    "DistribuicaoCotas" ADD CONSTRAINT "distribuicao_cotas_id_oferta_foreign"
    FOREIGN KEY("id_oferta") REFERENCES "Ofertas"("id");
ALTER TABLE
    "Documentos" ADD CONSTRAINT "documentos_id_candidatura_foreign"
    FOREIGN KEY("id_candidatura") REFERENCES "Candidaturas"("id");
ALTER TABLE
    "Candidaturas" ADD CONSTRAINT "candidaturas_id_usuario_foreign"
    FOREIGN KEY("id_usuario") REFERENCES "Usuarios"("id");
ALTER TABLE
    "Candidaturas" ADD CONSTRAINT "candidaturas_id_oferta_foreign"
    FOREIGN KEY("id_oferta") REFERENCES "Ofertas"("id");
ALTER TABLE
    "Candidaturas" ADD CONSTRAINT "candidaturas_id_edital_foreign"
    FOREIGN KEY("id_edital") REFERENCES "Editais"("id");
ALTER TABLE
    "Recursos" ADD CONSTRAINT "recursos_id_etapa_processo_foreign"
    FOREIGN KEY("id_etapa_processo") REFERENCES "Etapas Processo"("id");
ALTER TABLE
    "Enderecos" ADD CONSTRAINT "enderecos_id_usuario_foreign"
    FOREIGN KEY("id_usuario") REFERENCES "Usuarios"("id");
ALTER TABLE
    "Recursos" ADD CONSTRAINT "recursos_id_gestor_foreign"
    FOREIGN KEY("id_gestor") REFERENCES "Gestores"("id");
ALTER TABLE
    "Etapas Processo" ADD CONSTRAINT "etapas processo_id_candidatura_foreign"
    FOREIGN KEY("id_candidatura") REFERENCES "Candidaturas"("id");
ALTER TABLE
    "Etapas Processo" ADD CONSTRAINT "etapas processo_id_gestor_foreign"
    FOREIGN KEY("id_gestor") REFERENCES "Gestores"("id");
ALTER TABLE
    "Gestores" ADD CONSTRAINT "gestores_id_usuario_foreign"
    FOREIGN KEY("id_usuario") REFERENCES "Usuarios"("id");

CREATE INDEX IF NOT EXISTS "ofertas_id_edital_idx" ON "Ofertas"("id_edital");
CREATE INDEX IF NOT EXISTS "ofertas_id_curso_idx" ON "Ofertas"("id_curso");
CREATE INDEX IF NOT EXISTS "ofertas_id_campus_idx" ON "Ofertas"("id_campus");
CREATE INDEX IF NOT EXISTS "distribuicao_cotas_id_oferta_idx" ON "DistribuicaoCotas"("id_oferta");
CREATE INDEX IF NOT EXISTS "edital_arquivos_id_edital_idx" ON "EditalArquivos"("id_edital");
