-- W2 schema extras: contestacoes, notificacoes, carrossel, faixas SM, templates.
-- id_edital columns are soft references until W1 Editais table exists (FK deferred).
-- APIs/controllers for these tables land in later workstreams (W7, W29–W32).

CREATE TYPE TIPO_CONTESTACAO AS ENUM(
    'IMPUGNACAO',
    'RECURSO',
    'JUSTIFICATIVA'
);

CREATE TYPE STATUS_CONTESTACAO AS ENUM(
    'enviada',
    'em_analise',
    'deferida',
    'indeferida'
);

CREATE TABLE "Contestacoes"(
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "tipo" TIPO_CONTESTACAO NOT NULL,
    "status" STATUS_CONTESTACAO NOT NULL DEFAULT 'enviada',
    "id_edital" BIGINT NULL,
    "id_usuario" BIGINT NULL,
    "id_candidatura" BIGINT NULL,
    "texto" TEXT NOT NULL,
    "nome_anexo" VARCHAR(255) NULL,
    "arquivo_anexo" BYTEA NULL,
    "nome_requerente" VARCHAR(255) NULL,
    "email_requerente" VARCHAR(255) NULL,
    "criado_em" TIMESTAMP NOT NULL DEFAULT NOW(),
    "atualizado_em" TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TYPE ORIGEM_NOTIFICACAO AS ENUM('manual', 'automatico_cronograma');

CREATE TABLE "Notificacoes"(
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "titulo" VARCHAR(255) NOT NULL,
    "corpo" TEXT NOT NULL,
    "deep_link" VARCHAR(512) NULL,
    "origem" ORIGEM_NOTIFICACAO NOT NULL DEFAULT 'manual',
    "id_edital" BIGINT NULL,
    "filtro_campus" VARCHAR(255) NULL,
    "filtro_status" VARCHAR(255) NULL,
    "agendado_para" TIMESTAMP NULL,
    "enviado_em" TIMESTAMP NULL,
    "id_gestor" BIGINT NULL,
    "criado_em" TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE "NotificacaoLeituras"(
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "id_notificacao" BIGINT NOT NULL,
    "id_usuario" BIGINT NOT NULL,
    "lida_em" TIMESTAMP NULL,
    "criado_em" TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE "PreferenciasNotificacao"(
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "id_usuario" BIGINT NOT NULL,
    "silenciar_email" BOOLEAN NOT NULL DEFAULT FALSE,
    "silenciar_push" BOOLEAN NOT NULL DEFAULT FALSE,
    "silenciar_oficiais" BOOLEAN NOT NULL DEFAULT FALSE,
    "atualizado_em" TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TYPE TIPO_CARROSSEL AS ENUM('manual', 'auto_edital');

CREATE TABLE "CarrosselItens"(
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "tipo" TIPO_CARROSSEL NOT NULL DEFAULT 'manual',
    "rotulo" VARCHAR(255) NULL,
    "titulo" VARCHAR(255) NOT NULL,
    "subtitulo" VARCHAR(512) NULL,
    "cta_texto" VARCHAR(255) NULL,
    "cta_link" VARCHAR(512) NULL,
    "imagem_url" VARCHAR(1024) NULL,
    "icone" VARCHAR(255) NULL,
    "ordem" INT NOT NULL DEFAULT 0,
    "ativo" BOOLEAN NOT NULL DEFAULT TRUE,
    "id_edital" BIGINT NULL,
    "auto_edital_habilitado" BOOLEAN NOT NULL DEFAULT TRUE,
    "inicio_em" TIMESTAMP NULL,
    "fim_em" TIMESTAMP NULL,
    "criado_em" TIMESTAMP NOT NULL DEFAULT NOW(),
    "atualizado_em" TIMESTAMP NOT NULL DEFAULT NOW()
);

-- Singleton global config (SM reference). Faixas are ordered and optional (regra B).
CREATE TABLE "ConfiguracaoGlobal"(
    "id" INT PRIMARY KEY DEFAULT 1,
    "salario_minimo_referencia" DECIMAL(12, 2) NOT NULL DEFAULT 0,
    "atualizado_em" TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT "configuracao_global_singleton" CHECK ("id" = 1)
);

CREATE TABLE "FaixasSalarioMinimo"(
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "ordem" INT NOT NULL,
    "rotulo" VARCHAR(255) NOT NULL,
    "multiplicador_min" DECIMAL(8, 2) NULL,
    "multiplicador_max" DECIMAL(8, 2) NULL,
    "ativo" BOOLEAN NOT NULL DEFAULT TRUE,
    "criado_em" TIMESTAMP NOT NULL DEFAULT NOW()
);

-- W30 stubs: account library + per-edital editable copy + reply history on contestacao.
CREATE TABLE "TemplatesBiblioteca"(
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "titulo" VARCHAR(255) NOT NULL,
    "corpo" TEXT NOT NULL,
    "canal" VARCHAR(50) NULL,
    "tipo_uso" VARCHAR(50) NULL,
    "ativo" BOOLEAN NOT NULL DEFAULT TRUE,
    "criado_em" TIMESTAMP NOT NULL DEFAULT NOW(),
    "atualizado_em" TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE "TemplatesEdital"(
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "id_template_origem" BIGINT NULL,
    "id_edital" BIGINT NULL,
    "titulo" VARCHAR(255) NOT NULL,
    "corpo" TEXT NOT NULL,
    "canal" VARCHAR(50) NULL,
    "tipo_uso" VARCHAR(50) NULL,
    "criado_em" TIMESTAMP NOT NULL DEFAULT NOW(),
    "atualizado_em" TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE "ContestacaoHistorico"(
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "id_contestacao" BIGINT NOT NULL,
    "id_gestor" BIGINT NULL,
    "id_template_edital" BIGINT NULL,
    "canal" VARCHAR(50) NOT NULL,
    "corpo" TEXT NOT NULL,
    "enviado_em" TIMESTAMP NOT NULL DEFAULT NOW()
);

ALTER TABLE
    "Contestacoes" ADD CONSTRAINT "contestacoes_id_usuario_foreign"
    FOREIGN KEY("id_usuario") REFERENCES "Usuarios"("id");
ALTER TABLE
    "Contestacoes" ADD CONSTRAINT "contestacoes_id_candidatura_foreign"
    FOREIGN KEY("id_candidatura") REFERENCES "Candidaturas"("id");

ALTER TABLE
    "Notificacoes" ADD CONSTRAINT "notificacoes_id_gestor_foreign"
    FOREIGN KEY("id_gestor") REFERENCES "Gestores"("id");
ALTER TABLE
    "NotificacaoLeituras" ADD CONSTRAINT "notificacao_leituras_id_notificacao_foreign"
    FOREIGN KEY("id_notificacao") REFERENCES "Notificacoes"("id") ON DELETE CASCADE;
ALTER TABLE
    "NotificacaoLeituras" ADD CONSTRAINT "notificacao_leituras_id_usuario_foreign"
    FOREIGN KEY("id_usuario") REFERENCES "Usuarios"("id") ON DELETE CASCADE;
ALTER TABLE
    "PreferenciasNotificacao" ADD CONSTRAINT "preferencias_notificacao_id_usuario_foreign"
    FOREIGN KEY("id_usuario") REFERENCES "Usuarios"("id") ON DELETE CASCADE;

ALTER TABLE
    "TemplatesEdital" ADD CONSTRAINT "templates_edital_id_template_origem_foreign"
    FOREIGN KEY("id_template_origem") REFERENCES "TemplatesBiblioteca"("id");
ALTER TABLE
    "ContestacaoHistorico" ADD CONSTRAINT "contestacao_historico_id_contestacao_foreign"
    FOREIGN KEY("id_contestacao") REFERENCES "Contestacoes"("id") ON DELETE CASCADE;
ALTER TABLE
    "ContestacaoHistorico" ADD CONSTRAINT "contestacao_historico_id_gestor_foreign"
    FOREIGN KEY("id_gestor") REFERENCES "Gestores"("id");
ALTER TABLE
    "ContestacaoHistorico" ADD CONSTRAINT "contestacao_historico_id_template_edital_foreign"
    FOREIGN KEY("id_template_edital") REFERENCES "TemplatesEdital"("id");

CREATE UNIQUE INDEX IF NOT EXISTS "notificacao_leituras_unique"
    ON "NotificacaoLeituras"("id_notificacao", "id_usuario");
CREATE UNIQUE INDEX IF NOT EXISTS "preferencias_notificacao_usuario_unique"
    ON "PreferenciasNotificacao"("id_usuario");
CREATE UNIQUE INDEX IF NOT EXISTS "faixas_salario_minimo_ordem_unique"
    ON "FaixasSalarioMinimo"("ordem");

CREATE INDEX IF NOT EXISTS "contestacoes_id_edital_idx" ON "Contestacoes"("id_edital");
CREATE INDEX IF NOT EXISTS "contestacoes_id_usuario_idx" ON "Contestacoes"("id_usuario");
CREATE INDEX IF NOT EXISTS "contestacoes_status_idx" ON "Contestacoes"("status");
CREATE INDEX IF NOT EXISTS "notificacoes_id_edital_idx" ON "Notificacoes"("id_edital");
CREATE INDEX IF NOT EXISTS "carrossel_itens_ordem_idx" ON "CarrosselItens"("ordem");
CREATE INDEX IF NOT EXISTS "carrossel_itens_id_edital_idx" ON "CarrosselItens"("id_edital");
CREATE INDEX IF NOT EXISTS "templates_edital_id_edital_idx" ON "TemplatesEdital"("id_edital");
CREATE INDEX IF NOT EXISTS "contestacao_historico_id_contestacao_idx"
    ON "ContestacaoHistorico"("id_contestacao");
