-- W5: edital-level cronograma (REQ-1.2 / REQ-1.3 flags).
-- Distinct from legacy "Etapas Processo" (candidatura-scoped evaluation).

CREATE TYPE TIPO_ETAPA_CRONOGRAMA AS ENUM(
    'INSCRICAO',
    'HOMOLOGACAO',
    'SORTEIO_ELETRONICO',
    'RESULTADO_PRELIMINAR',
    'RECURSO_E_IMPUGNACAO',
    'RESULTADO_FINAL',
    'MATRICULA'
);

CREATE TYPE ETAPA_STATUS_OVERRIDE AS ENUM(
    'AUTOMATICO',
    'FORCADO_ABERTO',
    'BLOQUEADO_MANUALMENTE'
);

CREATE TABLE "CronogramaEtapas"(
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "id_edital" BIGINT NOT NULL,
    "tipo" TIPO_ETAPA_CRONOGRAMA NOT NULL,
    "nome_exibido" VARCHAR(255) NOT NULL,
    "data_inicio" TIMESTAMP NOT NULL,
    "data_fim" TIMESTAMP NOT NULL,
    "descricao" TEXT NULL,
    "ordem" INT NOT NULL,
    "override" ETAPA_STATUS_OVERRIDE NOT NULL DEFAULT 'AUTOMATICO',
    "elegivel_impugnacao" BOOLEAN NOT NULL DEFAULT FALSE,
    "elegivel_recurso" BOOLEAN NOT NULL DEFAULT FALSE,
    "template_instrucao_id" BIGINT NULL,
    CONSTRAINT "cronograma_etapas_data_fim_gte_inicio_chk"
        CHECK ("data_fim" >= "data_inicio")
);

ALTER TABLE
    "CronogramaEtapas" ADD CONSTRAINT "cronograma_etapas_id_edital_foreign"
    FOREIGN KEY("id_edital") REFERENCES "Editais"("id") ON DELETE CASCADE;

ALTER TABLE
    "CronogramaEtapas" ADD CONSTRAINT "cronograma_etapas_template_instrucao_foreign"
    FOREIGN KEY("template_instrucao_id") REFERENCES "TemplatesEdital"("id");

CREATE INDEX IF NOT EXISTS "cronograma_etapas_id_edital_ordem_idx"
    ON "CronogramaEtapas"("id_edital", "ordem");
