-- W6: document types builder (REQ-1.4) + delivery modes (REQ-1.6).
-- Distinct from legacy "Documentos" (candidatura file rows).

CREATE TYPE FASE_DOCUMENTO AS ENUM(
    'INSCRICAO',
    'MATRICULA'
);

CREATE TYPE CAMPO_FORMULARIO_TIPO AS ENUM(
    'texto',
    'numero',
    'documento'
);

CREATE TYPE MODO_ENTREGA AS ENUM(
    'PRESENCIAL',
    'ONLINE'
);

CREATE TYPE SUBTIPO_ENTREGA_ONLINE AS ENUM(
    'UPLOAD_NATIVO_PWA',
    'URL_FORMULARIO_EXTERNO',
    'EMAIL_INSTITUCIONAL'
);

CREATE TABLE "TiposDocumento"(
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "id_edital" BIGINT NOT NULL,
    "nome" VARCHAR(255) NOT NULL,
    "descricao" TEXT NULL,
    "obrigatorio" BOOLEAN NOT NULL DEFAULT TRUE,
    "formatos" TEXT[] NOT NULL DEFAULT ARRAY['pdf']::TEXT[],
    "tamanho_max_bytes" INT NOT NULL DEFAULT 15728640,
    "template_nome" VARCHAR(255) NULL,
    "template_mime" VARCHAR(255) NULL,
    "template_arquivo" BYTEA NULL,
    "fase" FASE_DOCUMENTO NOT NULL,
    "tipo_cota" VARCHAR(64) NULL,
    "ordem" INT NOT NULL,
    CONSTRAINT "tipos_documento_tamanho_positive_chk"
        CHECK ("tamanho_max_bytes" > 0),
    CONSTRAINT "tipos_documento_nome_nonempty_chk"
        CHECK (LENGTH(TRIM("nome")) > 0)
);

ALTER TABLE
    "TiposDocumento" ADD CONSTRAINT "tipos_documento_id_edital_foreign"
    FOREIGN KEY("id_edital") REFERENCES "Editais"("id") ON DELETE CASCADE;

CREATE INDEX IF NOT EXISTS "tipos_documento_id_edital_ordem_idx"
    ON "TiposDocumento"("id_edital", "ordem");

CREATE TABLE "TipoDocumentoCampos"(
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "id_tipo_documento" BIGINT NOT NULL,
    "tipo" CAMPO_FORMULARIO_TIPO NOT NULL,
    "rotulo" VARCHAR(255) NOT NULL,
    "obrigatorio" BOOLEAN NOT NULL DEFAULT FALSE,
    "ordem" INT NOT NULL,
    "formatos" TEXT[] NULL,
    "tamanho_max_bytes" INT NULL,
    CONSTRAINT "tipo_documento_campos_rotulo_nonempty_chk"
        CHECK (LENGTH(TRIM("rotulo")) > 0),
    CONSTRAINT "tipo_documento_campos_tamanho_positive_chk"
        CHECK ("tamanho_max_bytes" IS NULL OR "tamanho_max_bytes" > 0)
);

ALTER TABLE
    "TipoDocumentoCampos" ADD CONSTRAINT "tipo_documento_campos_tipo_documento_foreign"
    FOREIGN KEY("id_tipo_documento") REFERENCES "TiposDocumento"("id") ON DELETE CASCADE;

CREATE INDEX IF NOT EXISTS "tipo_documento_campos_tipo_ordem_idx"
    ON "TipoDocumentoCampos"("id_tipo_documento", "ordem");

CREATE TABLE "ConfiguracaoEntregaDocumental"(
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "id_edital" BIGINT NOT NULL,
    "id_campus" BIGINT NOT NULL,
    "id_curso" BIGINT NOT NULL,
    "id_cronograma_etapa" BIGINT NOT NULL,
    "modo" MODO_ENTREGA NOT NULL,
    "local_nome" VARCHAR(255) NULL,
    "endereco" TEXT NULL,
    "horario" TEXT NULL,
    "contactos" TEXT NULL,
    "subtipo_online" SUBTIPO_ENTREGA_ONLINE NULL,
    "url_externa" VARCHAR(2048) NULL,
    "email_institucional" VARCHAR(255) NULL,
    "instrucoes" TEXT NULL,
    CONSTRAINT "config_entrega_unique_vinculo"
        UNIQUE ("id_edital", "id_campus", "id_curso", "id_cronograma_etapa"),
    CONSTRAINT "config_entrega_presencial_chk"
        CHECK (
            "modo" <> 'PRESENCIAL'
            OR (
                "local_nome" IS NOT NULL AND LENGTH(TRIM("local_nome")) > 0
                AND "endereco" IS NOT NULL AND LENGTH(TRIM("endereco")) > 0
            )
        ),
    CONSTRAINT "config_entrega_online_chk"
        CHECK (
            "modo" <> 'ONLINE'
            OR "subtipo_online" IS NOT NULL
        )
);

ALTER TABLE
    "ConfiguracaoEntregaDocumental" ADD CONSTRAINT "config_entrega_id_edital_foreign"
    FOREIGN KEY("id_edital") REFERENCES "Editais"("id") ON DELETE CASCADE;

ALTER TABLE
    "ConfiguracaoEntregaDocumental" ADD CONSTRAINT "config_entrega_id_campus_foreign"
    FOREIGN KEY("id_campus") REFERENCES "Campus"("id");

ALTER TABLE
    "ConfiguracaoEntregaDocumental" ADD CONSTRAINT "config_entrega_id_curso_foreign"
    FOREIGN KEY("id_curso") REFERENCES "Cursos"("id");

ALTER TABLE
    "ConfiguracaoEntregaDocumental" ADD CONSTRAINT "config_entrega_id_cronograma_etapa_foreign"
    FOREIGN KEY("id_cronograma_etapa") REFERENCES "CronogramaEtapas"("id") ON DELETE CASCADE;

CREATE INDEX IF NOT EXISTS "config_entrega_id_edital_idx"
    ON "ConfiguracaoEntregaDocumental"("id_edital");
