-- W8: account-base document types (REQ-1.5) + candidate Meus Dados files.
-- Depends on 01_schemas (Usuarios), 08_doc_types_delivery (TiposDocumento, fase_documento).

CREATE TABLE "TiposDocumentoBase"(
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "nome" VARCHAR(255) NOT NULL,
    "descricao" TEXT NULL,
    "obrigatorio" BOOLEAN NOT NULL DEFAULT TRUE,
    "formatos" TEXT[] NOT NULL DEFAULT ARRAY['pdf']::TEXT[],
    "tamanho_max_bytes" INT NOT NULL DEFAULT 15728640,
    "template_nome" VARCHAR(255) NULL,
    "template_mime" VARCHAR(255) NULL,
    "template_arquivo" BYTEA NULL,
    "fase" FASE_DOCUMENTO NOT NULL DEFAULT 'INSCRICAO',
    "ordem" INT NOT NULL,
    "ativo" BOOLEAN NOT NULL DEFAULT TRUE,
    "criado_em" TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT "tipos_documento_base_tamanho_positive_chk"
        CHECK ("tamanho_max_bytes" > 0),
    CONSTRAINT "tipos_documento_base_nome_nonempty_chk"
        CHECK (LENGTH(TRIM("nome")) > 0)
);

CREATE INDEX IF NOT EXISTS "tipos_documento_base_ordem_idx"
    ON "TiposDocumentoBase"("ordem", "id");

CREATE INDEX IF NOT EXISTS "tipos_documento_base_ativo_idx"
    ON "TiposDocumentoBase"("ativo");

-- Inheritance link: edital tipo copied from account base (deselectable = delete edital row).
ALTER TABLE "TiposDocumento"
    ADD COLUMN IF NOT EXISTS "id_tipo_base" BIGINT NULL;

ALTER TABLE "TiposDocumento"
    DROP CONSTRAINT IF EXISTS "tipos_documento_id_tipo_base_foreign";

ALTER TABLE "TiposDocumento"
    ADD CONSTRAINT "tipos_documento_id_tipo_base_foreign"
    FOREIGN KEY("id_tipo_base") REFERENCES "TiposDocumentoBase"("id");

CREATE INDEX IF NOT EXISTS "tipos_documento_id_tipo_base_idx"
    ON "TiposDocumento"("id_tipo_base");

-- Candidate Meus Dados: one current file per account-base type.
CREATE TABLE "DocumentosConta"(
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "id_usuario" BIGINT NOT NULL,
    "id_tipo_base" BIGINT NOT NULL,
    "nome_arquivo" VARCHAR(255) NOT NULL,
    "mime" VARCHAR(255) NULL,
    "arquivo" BYTEA NOT NULL,
    "atualizado_em" TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT "documentos_conta_usuario_tipo_unique"
        UNIQUE ("id_usuario", "id_tipo_base"),
    CONSTRAINT "documentos_conta_nome_nonempty_chk"
        CHECK (LENGTH(TRIM("nome_arquivo")) > 0)
);

ALTER TABLE "DocumentosConta"
    ADD CONSTRAINT "documentos_conta_id_usuario_foreign"
    FOREIGN KEY("id_usuario") REFERENCES "Usuarios"("id") ON DELETE CASCADE;

ALTER TABLE "DocumentosConta"
    ADD CONSTRAINT "documentos_conta_id_tipo_base_foreign"
    FOREIGN KEY("id_tipo_base") REFERENCES "TiposDocumentoBase"("id");

CREATE INDEX IF NOT EXISTS "documentos_conta_id_usuario_idx"
    ON "DocumentosConta"("id_usuario");
