-- W17: respostas socioeconómicas (REQ-2.3 / REQ-1.7)
-- Snapshot de faixa no submit; soft-archive on cota change; regra B = incompleto.

CREATE TABLE IF NOT EXISTS "RespostasSocioeconomicas"(
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "id_candidatura" BIGINT NOT NULL,
    "id_faixa" BIGINT NULL,
    "numero_pessoas" INT NULL,
    "faixa_rotulo_snapshot" VARCHAR(255) NULL,
    "faixa_multiplicador_min_snapshot" DECIMAL(8, 2) NULL,
    "faixa_multiplicador_max_snapshot" DECIMAL(8, 2) NULL,
    "salario_minimo_ref_snapshot" DECIMAL(12, 2) NULL,
    "incompleto_regra_b" BOOLEAN NOT NULL DEFAULT FALSE,
    "arquivado" BOOLEAN NOT NULL DEFAULT FALSE,
    "campos_extras" JSONB NULL,
    "criado_em" TIMESTAMP NOT NULL DEFAULT NOW(),
    "arquivado_em" TIMESTAMP NULL,
    CONSTRAINT "respostas_socio_numero_pessoas_check"
        CHECK ("numero_pessoas" IS NULL OR "numero_pessoas" >= 1)
);

ALTER TABLE
    "RespostasSocioeconomicas" ADD CONSTRAINT "respostas_socio_id_candidatura_foreign"
    FOREIGN KEY("id_candidatura") REFERENCES "Candidaturas"("id") ON DELETE CASCADE;
ALTER TABLE
    "RespostasSocioeconomicas" ADD CONSTRAINT "respostas_socio_id_faixa_foreign"
    FOREIGN KEY("id_faixa") REFERENCES "FaixasSalarioMinimo"("id");

-- At most one active (non-archived) answer per candidatura.
CREATE UNIQUE INDEX IF NOT EXISTS "respostas_socio_candidatura_ativa_unique"
    ON "RespostasSocioeconomicas"("id_candidatura")
    WHERE "arquivado" = FALSE;

CREATE INDEX IF NOT EXISTS "respostas_socio_id_faixa_idx"
    ON "RespostasSocioeconomicas"("id_faixa");
CREATE INDEX IF NOT EXISTS "respostas_socio_id_candidatura_idx"
    ON "RespostasSocioeconomicas"("id_candidatura");
