-- W20–W25: lotes de contas/inscrições, classificação AC↔RV, chamadas e dashboard.
-- REQ-2.8 (ativo/inativo + lotes), REQ-3.1/3.2/3.3 (remanescentes e fallback),
-- REQ-3.4 (chamadas e espera), REQ-3.5 (matriculado como status final do ciclo).

-- REQ-2.8: desabilitar acesso bloqueia login mas mantém as inscrições.
ALTER TABLE "Usuarios" ADD COLUMN IF NOT EXISTS "ativo" BOOLEAN NOT NULL DEFAULT TRUE;

-- REQ-3.5: status final do ciclo (ato do aluno, importado pelos campi).
ALTER TYPE STATUS_CANDIDATURA ADD VALUE IF NOT EXISTS 'matriculado';

-- REQ-2.8 / REQ-2.2: importação SiSU não passa pela unicidade do PWA, logo o
-- índice parcial ativo deixa de considerar as candidaturas de tipo_ingresso sisu.
DROP INDEX IF EXISTS "candidaturas_usuario_edital_active_unique";
CREATE UNIQUE INDEX "candidaturas_usuario_edital_active_unique"
    ON "Candidaturas"("id_usuario", "id_edital")
    WHERE "status" <> 'cancelada'
      AND ("tipo_ingresso" IS NULL OR "tipo_ingresso" <> 'sisu');

DO $$ BEGIN
    CREATE TYPE LISTA_CLASSIFICACAO AS ENUM('chamada_regular', 'espera');
EXCEPTION
    WHEN duplicate_object THEN NULL;
END $$;

-- REQ-3.4: cada chamada congela as vagas ofertadas e as listas geradas.
CREATE TABLE IF NOT EXISTS "Chamadas"(
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "id_oferta" BIGINT NOT NULL,
    "numero" INT NOT NULL,
    "fallback_ac_para_rv" BOOLEAN NOT NULL DEFAULT FALSE,
    "observacao" VARCHAR(255) NULL,
    "criado_em" TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT "chamadas_numero_check" CHECK ("numero" >= 1)
);

ALTER TABLE
    "Chamadas" ADD CONSTRAINT "chamadas_id_oferta_foreign"
    FOREIGN KEY("id_oferta") REFERENCES "Ofertas"("id") ON DELETE CASCADE;

CREATE UNIQUE INDEX IF NOT EXISTS "chamadas_oferta_numero_unique"
    ON "Chamadas"("id_oferta", "numero");
CREATE INDEX IF NOT EXISTS "chamadas_id_oferta_idx" ON "Chamadas"("id_oferta");

-- REQ-3.1: vagas por cota em cada chamada; as não preenchidas viram AC na seguinte.
CREATE TABLE IF NOT EXISTS "ChamadaVagas"(
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "id_chamada" BIGINT NOT NULL,
    "tipo_cota" VARCHAR(50) NOT NULL,
    "vagas" SMALLINT NOT NULL DEFAULT 0,
    "preenchidas" SMALLINT NOT NULL DEFAULT 0,
    "remanescentes" SMALLINT NOT NULL DEFAULT 0,
    CONSTRAINT "chamada_vagas_vagas_check" CHECK ("vagas" >= 0),
    CONSTRAINT "chamada_vagas_preenchidas_check" CHECK ("preenchidas" >= 0)
);

ALTER TABLE
    "ChamadaVagas" ADD CONSTRAINT "chamada_vagas_id_chamada_foreign"
    FOREIGN KEY("id_chamada") REFERENCES "Chamadas"("id") ON DELETE CASCADE;

CREATE UNIQUE INDEX IF NOT EXISTS "chamada_vagas_chamada_cota_unique"
    ON "ChamadaVagas"("id_chamada", "tipo_cota");
CREATE INDEX IF NOT EXISTS "chamada_vagas_id_chamada_idx"
    ON "ChamadaVagas"("id_chamada");

-- REQ-3.2 / 3.3: posição em cada lista; realocado_para_ac marca o cotista que
-- entrou pela ampla concorrência e por isso libertou a vaga da cota.
CREATE TABLE IF NOT EXISTS "ClassificacaoItens"(
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "id_chamada" BIGINT NOT NULL,
    "id_candidatura" BIGINT NOT NULL,
    "lista" LISTA_CLASSIFICACAO NOT NULL,
    "tipo_cota" VARCHAR(50) NOT NULL,
    "posicao" INT NOT NULL,
    "realocado_para_ac" BOOLEAN NOT NULL DEFAULT FALSE,
    "criado_em" TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT "classificacao_itens_posicao_check" CHECK ("posicao" >= 1)
);

ALTER TABLE
    "ClassificacaoItens" ADD CONSTRAINT "classificacao_itens_id_chamada_foreign"
    FOREIGN KEY("id_chamada") REFERENCES "Chamadas"("id") ON DELETE CASCADE;
ALTER TABLE
    "ClassificacaoItens" ADD CONSTRAINT "classificacao_itens_id_candidatura_foreign"
    FOREIGN KEY("id_candidatura") REFERENCES "Candidaturas"("id") ON DELETE CASCADE;

CREATE UNIQUE INDEX IF NOT EXISTS "classificacao_itens_chamada_candidatura_unique"
    ON "ClassificacaoItens"("id_chamada", "id_candidatura");
CREATE INDEX IF NOT EXISTS "classificacao_itens_id_chamada_idx"
    ON "ClassificacaoItens"("id_chamada");
CREATE INDEX IF NOT EXISTS "classificacao_itens_id_candidatura_idx"
    ON "ClassificacaoItens"("id_candidatura");
CREATE INDEX IF NOT EXISTS "classificacao_itens_lista_idx"
    ON "ClassificacaoItens"("id_chamada", "lista", "posicao");
