-- W26/W27: document upload metadata, audit, human homologation + reason catalogue.
-- Fresh volumes apply via docker-entrypoint-initdb.d; existing volumes need manual apply.

CREATE TABLE IF NOT EXISTS "MotivosHomologacaoDocumento"(
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "codigo" VARCHAR(64) NOT NULL,
    "descricao" VARCHAR(255) NOT NULL,
    "ativo" BOOLEAN NOT NULL DEFAULT TRUE,
    "exige_texto_livre" BOOLEAN NOT NULL DEFAULT FALSE,
    "criado_em" TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT "motivos_homologacao_documento_codigo_unique" UNIQUE ("codigo")
);

ALTER TABLE "Documentos"
    ADD COLUMN IF NOT EXISTS "mime" VARCHAR(255) NULL;

ALTER TABLE "Documentos"
    ADD COLUMN IF NOT EXISTS "fase" VARCHAR(32) NOT NULL DEFAULT 'INSCRICAO';

ALTER TABLE "Documentos"
    ADD COLUMN IF NOT EXISTS "id_motivo" INT NULL;

ALTER TABLE "Documentos"
    ADD COLUMN IF NOT EXISTS "motivo_livre" TEXT NULL;

ALTER TABLE "Documentos"
    ADD COLUMN IF NOT EXISTS "decidido_em" TIMESTAMP NULL;

ALTER TABLE "Documentos"
    ADD COLUMN IF NOT EXISTS "id_gestor_decisao" BIGINT NULL;

ALTER TABLE "Documentos"
    ADD COLUMN IF NOT EXISTS "atualizado_em" TIMESTAMP NOT NULL DEFAULT NOW();

ALTER TABLE "Documentos"
    ADD COLUMN IF NOT EXISTS "anexo_decisao_nome" VARCHAR(255) NULL;

ALTER TABLE "Documentos"
    ADD COLUMN IF NOT EXISTS "anexo_decisao" BYTEA NULL;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'documentos_id_motivo_foreign'
    ) THEN
        ALTER TABLE "Documentos"
            ADD CONSTRAINT "documentos_id_motivo_foreign"
            FOREIGN KEY ("id_motivo")
            REFERENCES "MotivosHomologacaoDocumento"("id")
            ON DELETE SET NULL;
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS "DocumentosAuditoria"(
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "id_documento" INT NOT NULL,
    "id_candidatura" BIGINT NOT NULL,
    "acao" VARCHAR(64) NOT NULL,
    "id_usuario" BIGINT NULL,
    "id_gestor" BIGINT NULL,
    "detalhe" TEXT NULL,
    "criado_em" TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS "documentos_auditoria_documento_idx"
    ON "DocumentosAuditoria"("id_documento");

CREATE INDEX IF NOT EXISTS "documentos_auditoria_candidatura_idx"
    ON "DocumentosAuditoria"("id_candidatura");

CREATE INDEX IF NOT EXISTS "documentos_status_fase_idx"
    ON "Documentos"("status_documento", "fase");

ALTER TABLE "Candidaturas"
    ADD COLUMN IF NOT EXISTS "observacoes_admin" TEXT NULL;

-- Optional IA suggestion column (W28 consumes; W27 ensures it never auto-decides).
ALTER TABLE "Documentos"
    ADD COLUMN IF NOT EXISTS "sugestao_ia" TEXT NULL;

INSERT INTO "MotivosHomologacaoDocumento"("codigo", "descricao", "ativo", "exige_texto_livre")
VALUES
    ('ILEGIVEL', 'Documento ilegível ou de baixa qualidade', TRUE, FALSE),
    ('INCOMPLETO', 'Documento incompleto ou páginas faltando', TRUE, FALSE),
    ('FORA_PRAZO', 'Documento fora do prazo / validade', TRUE, FALSE),
    ('TIPO_ERRADO', 'Tipo de documento incorreto para a exigência', TRUE, FALSE),
    ('DADOS_DIVERGENTES', 'Dados divergentes do cadastro do candidato', TRUE, FALSE),
    ('OUTRO', 'Outro motivo (texto livre obrigatório)', TRUE, TRUE)
ON CONFLICT ("codigo") DO NOTHING;

-- Legacy Documentos.criado_em had no DEFAULT; TypeORM CreateDateColumn may emit DEFAULT.
ALTER TABLE "Documentos"
    ALTER COLUMN "criado_em" SET DEFAULT NOW();

ALTER TABLE "Documentos"
    ALTER COLUMN "atualizado_em" SET DEFAULT NOW();
