-- W31 — Notificações: delivery outbox + reminder config (REQ-6.1)
-- Base tables Notificacoes / NotificacaoLeituras / PreferenciasNotificacao: 04_schema_extras.sql

CREATE TYPE STATUS_ENTREGA_NOTIFICACAO AS ENUM(
  'pendente',
  'enviado',
  'falhou',
  'omitido_preferencia',
  'adiado_smtp'
);

CREATE TYPE CANAL_NOTIFICACAO AS ENUM('pwa', 'email');

CREATE TABLE "NotificacaoEntregas"(
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "id_notificacao" BIGINT NOT NULL,
    "id_usuario" BIGINT NOT NULL,
    "canal" CANAL_NOTIFICACAO NOT NULL,
    "status" STATUS_ENTREGA_NOTIFICACAO NOT NULL DEFAULT 'pendente',
    "destino" VARCHAR(512) NULL,
    "detalhe" TEXT NULL,
    "criado_em" TIMESTAMP NOT NULL DEFAULT NOW(),
    "processado_em" TIMESTAMP NULL
);

CREATE INDEX "idx_notificacao_entregas_notif" ON "NotificacaoEntregas"("id_notificacao");
CREATE INDEX "idx_notificacao_entregas_status" ON "NotificacaoEntregas"("status");
CREATE INDEX "idx_notificacao_entregas_usuario" ON "NotificacaoEntregas"("id_usuario");

ALTER TABLE "NotificacaoEntregas"
  ADD CONSTRAINT "fk_notif_entrega_notif"
  FOREIGN KEY ("id_notificacao") REFERENCES "Notificacoes"("id") ON DELETE CASCADE;

ALTER TABLE "NotificacaoEntregas"
  ADD CONSTRAINT "fk_notif_entrega_usuario"
  FOREIGN KEY ("id_usuario") REFERENCES "Usuarios"("id") ON DELETE CASCADE;

CREATE TYPE TIPO_LEMBRETE_NOTIFICACAO AS ENUM(
  'matricula_prazo',
  'etapa_inicio',
  'etapa_fim'
);

CREATE TABLE "LembretesNotificacao"(
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "tipo" TIPO_LEMBRETE_NOTIFICACAO NOT NULL DEFAULT 'matricula_prazo',
    "id_edital" BIGINT NULL,
    "offset_horas" INT NOT NULL DEFAULT -48,
    "titulo_template" VARCHAR(255) NOT NULL,
    "corpo_template" TEXT NOT NULL,
    "ativo" BOOLEAN NOT NULL DEFAULT TRUE,
    "ultimo_processamento_em" TIMESTAMP NULL,
    "criado_em" TIMESTAMP NOT NULL DEFAULT NOW(),
    "atualizado_em" TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE INDEX "idx_lembretes_notif_ativo" ON "LembretesNotificacao"("ativo");
CREATE INDEX "idx_lembretes_notif_edital" ON "LembretesNotificacao"("id_edital");

ALTER TABLE "LembretesNotificacao"
  ADD CONSTRAINT "fk_lembrete_notif_edital"
  FOREIGN KEY ("id_edital") REFERENCES "Editais"("id") ON DELETE CASCADE;

-- Dedup: one reminder fire per (lembrete, etapa, user) window key
CREATE TABLE "LembreteDisparos"(
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "id_lembrete" BIGINT NOT NULL,
    "id_etapa" BIGINT NOT NULL,
    "id_usuario" BIGINT NOT NULL,
    "id_notificacao" BIGINT NULL,
    "chave" VARCHAR(128) NOT NULL,
    "criado_em" TIMESTAMP NOT NULL DEFAULT NOW(),
    CONSTRAINT "uq_lembrete_disparo_chave" UNIQUE ("chave")
);

ALTER TABLE "LembreteDisparos"
  ADD CONSTRAINT "fk_lembrete_disparo_lembrete"
  FOREIGN KEY ("id_lembrete") REFERENCES "LembretesNotificacao"("id") ON DELETE CASCADE;

ALTER TABLE "LembreteDisparos"
  ADD CONSTRAINT "fk_lembrete_disparo_etapa"
  FOREIGN KEY ("id_etapa") REFERENCES "CronogramaEtapas"("id") ON DELETE CASCADE;

ALTER TABLE "LembreteDisparos"
  ADD CONSTRAINT "fk_lembrete_disparo_usuario"
  FOREIGN KEY ("id_usuario") REFERENCES "Usuarios"("id") ON DELETE CASCADE;

-- Seed default matrícula due reminder (48h before etapa fim)
INSERT INTO "LembretesNotificacao"(
  "tipo", "id_edital", "offset_horas", "titulo_template", "corpo_template", "ativo"
) VALUES (
  'matricula_prazo',
  NULL,
  -48,
  'Prazo de matrícula se aproximando',
  'A etapa de matrícula do processo {{edital}} encerra em breve ({{data_fim}}). Regularize sua matrícula pelo aplicativo.',
  TRUE
);
