-- W33 — Hub FAQ / contactos + LGPD text on ConfiguracaoGlobal (REQ-6.3 / REQ-6.4).
-- Next free number after 20_w31_notificacoes.sql (plan name 18_w33 was stale).

ALTER TABLE "ConfiguracaoGlobal"
  ADD COLUMN IF NOT EXISTS "texto_lgpd" TEXT NULL;

COMMENT ON COLUMN "ConfiguracaoGlobal"."texto_lgpd" IS
  'Optional admin LGPD copy for PWA. NULL → client fallback (Lei 13.709/2018 + reitoria@ifb.edu.br).';

CREATE TABLE IF NOT EXISTS "HubFaqItens" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "pergunta" VARCHAR(500) NOT NULL,
  "resposta" TEXT NOT NULL,
  "ordem" INT NOT NULL DEFAULT 0,
  "ativo" BOOLEAN NOT NULL DEFAULT TRUE,
  "criado_em" TIMESTAMP NOT NULL DEFAULT NOW(),
  "atualizado_em" TIMESTAMP NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS "HubContactos" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "titulo" VARCHAR(255) NOT NULL,
  "valor" VARCHAR(500) NOT NULL,
  "tipo" VARCHAR(50) NOT NULL DEFAULT 'outro',
  "ordem" INT NOT NULL DEFAULT 0,
  "ativo" BOOLEAN NOT NULL DEFAULT TRUE,
  "criado_em" TIMESTAMP NOT NULL DEFAULT NOW(),
  "atualizado_em" TIMESTAMP NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE "HubFaqItens" IS 'REQ-6.3 Hub FAQ items managed in admin.';
COMMENT ON TABLE "HubContactos" IS
  'REQ-6.3 Hub contactos. tipo=email|telefone|url|endereco|outro.';

-- Idempotent seed FAQ (only when empty)
INSERT INTO "HubFaqItens" ("pergunta", "resposta", "ordem", "ativo")
SELECT v.pergunta, v.resposta, v.ordem, TRUE
FROM (
  VALUES
    (
      'Como me inscrever?',
      'Acesse a Home, escolha um curso com inscrição aberta e complete o formulário. É permitido apenas um curso por edital.',
      1
    ),
    (
      'Onde enviar documentos?',
      'Após a inscrição, use a área Documentos do aplicativo conforme a etapa e o campus do edital.',
      2
    ),
    (
      'Como funciona o sorteio?',
      'Quando o edital usa sorteio (ou fase preliminar híbrida), a classificação é publicada no cronograma. Consulte o PDF do edital.',
      3
    ),
    (
      'Qual é o prazo?',
      'Os prazos variam por edital. Veja o cronograma na ficha do processo e os avisos na aba Avisos.',
      4
    )
) AS v(pergunta, resposta, ordem)
WHERE NOT EXISTS (SELECT 1 FROM "HubFaqItens" LIMIT 1);

INSERT INTO "HubContactos" ("titulo", "valor", "tipo", "ordem", "ativo")
SELECT v.titulo, v.valor, v.tipo, v.ordem, TRUE
FROM (
  VALUES
    ('Reitoria IFB (LGPD / remoção de dados)', 'reitoria@ifb.edu.br', 'email', 1),
    ('Central de Atendimento', 'https://www.ifb.edu.br', 'url', 2)
) AS v(titulo, valor, tipo, ordem)
WHERE NOT EXISTS (SELECT 1 FROM "HubContactos" LIMIT 1);
