CREATE TABLE "Cursos"(
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "nome" VARCHAR(255) NOT NULL,
    "duracao_semestres" VARCHAR(255) NOT NULL,
    "campus" VARCHAR(255) NOT NULL,
    "modalidade" VARCHAR(255) NOT NULL,
    "turno" VARCHAR(255) NOT NULL,
    "vagas_totais" SMALLINT NOT NULL,
    "vagas_cotas_pii" SMALLINT NULL,
    "vagas_pcd" SMALLINT NULL,
    "data_inicio_inscricao" DATE NOT NULL,
    "data_fim_inscricao" DATE NOT NULL,
    "area_conhecimento" VARCHAR(255)
);
CREATE TABLE "Usuarios"(
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "nome_completo" VARCHAR(255) NOT NULL,
    "email" VARCHAR(255) NOT NULL,
    "CPF" VARCHAR(255) NOT NULL,
    "data_nascimento" DATE NOT NULL,
    "telefone" VARCHAR(255) NOT NULL,
    "nome_RG" VARCHAR(255) NOT NULL,
    "RG" BYTEA NOT NULL,
    "nome_historico_escolar" VARCHAR(255) NOT NULL,
    "historico_escolar" BYTEA NOT NULL,
    "renda_familiar" DECIMAL(8, 2) NOT NULL,
    "foto_alt" VARCHAR(255) NOT NULL,
    "foto" BYTEA NOT NULL,
    "ppi" VARCHAR(255) NULL,
    "pcd" BOOLEAN NOT NULL,
    "criado_em" TIMESTAMP NOT NULL,
    "atualizado_em" TIMESTAMP NOT NULL,
    "token" VARCHAR(255) NOT NULL
);
CREATE TABLE "Enderecos"(
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "id_usuario" BIGINT NOT NULL,
    "estado" VARCHAR(255) NOT NULL,
    "cidade" VARCHAR(255) NOT NULL,
    "CEP" VARCHAR(255) NOT NULL,
    "logradouro" VARCHAR(255) NOT NULL,
    "bairro" VARCHAR(255) NOT NULL,
    "numero_residencia" VARCHAR(255) NOT NULL,
    "complemento" VARCHAR(255) NULL
);
CREATE TYPE STATUS_CANDIDATURA AS ENUM(
        'inscricao_recebida',
        'pre_selecionado',
        'analise_documental',
        'aprovado',
        'reprovado'
    );
CREATE TYPE TIPO_INGRESSO AS ENUM(
        'sisu',
        'sorteio',
        'ordem_chegada',
        'analise_curricular',
        'transferencia'
    );
CREATE TYPE TIPO_VAGA AS ENUM('AC', 'PCD', 'PII', 'escola_publica');
CREATE TABLE "Candidaturas"(
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "id_usuario" BIGINT NOT NULL,
    "id_curso" BIGINT NOT NULL,
    "data_inscricao" BIGINT NOT NULL,
    "status" STATUS_CANDIDATURA NOT NULL DEFAULT 'inscricao_recebida',
    "tipo_ingresso" TIPO_INGRESSO NULL,
    "tipo_vaga" TIPO_VAGA NOT NULL DEFAULT 'AC'
);
CREATE TABLE "Documentos"(
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "id_candidatura" BIGINT NOT NULL,
    "tipo_documento" VARCHAR(255) NOT NULL,
    "nome_arquivo" VARCHAR(255) NOT NULL,
    "arquivo" BYTEA NOT NULL,
    "status_documento" VARCHAR(255) NOT NULL DEFAULT 'em_analise',
    "criado_em" TIMESTAMP NOT NULL
);
CREATE TYPE ETAPA_PROCESSO AS ENUM(
        'periodo_inscricoes'
        'manifestacao_interesse',
        'entrega_documental'
        'analise_documental',
        'publicacao_resultado_preliminar',
        'apresentacao_recurso',
        'analise_recurso',
        'publicacao_resultado_final',
        'matricula',
        'encerrado'
    );
CREATE TYPE RESULTADO_ETAPA AS ENUM('aprovado', 'reprovado', 'pendente');
CREATE TABLE "Etapas Processo"(
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "id_candidatura" BIGINT NOT NULL,
    "id_gestor" BIGINT NOT NULL,
    "tipo_etapa" ETAPA_PROCESSO NOT NULL DEFAULT 'periodo_inscricoes',
    "status" RESULTADO_ETAPA NOT NULL DEFAULT 'pendente',
    "pontuacao" DECIMAL(8, 2) NULL,
    "observacoes" VARCHAR(255) NOT NULL,
    "data_realizacao" DATE NOT NULL,
    "prazo" DATE NOT NULL
);
-- 
CREATE TABLE "Gestores"(
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "id_usuario" BIGINT NOT NULL,
    "funcao" VARCHAR(255) NULL
);
CREATE TYPE STATUS_RECURSO AS ENUM(
        'aberto',
        'em_analise',
        'deferido',
        'indeferido'
    );
CREATE TABLE "Recursos"(
    "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "id_etapa_processo" BIGINT NOT NULL,
    "data_solicitacao" DATE NOT NULL,
    "titulo" VARCHAR(255) NOT NULL,
    "nome_anexo" VARCHAR(255) NOT NULL,
    "arquivo_anexo" BYTEA NOT NULL,
    "status" STATUS_RECURSO NOT NULL DEFAULT 'aberto',
    "id_gestor" BIGINT NOT NULL,
    "observacoes" VARCHAR(255) NOT NULL
);
ALTER TABLE
    "Documentos" ADD CONSTRAINT "documentos_id_candidatura_foreign" FOREIGN KEY("id_candidatura") REFERENCES "Candidaturas"("id");
ALTER TABLE
    "Candidaturas" ADD CONSTRAINT "candidaturas_id_usuario_foreign" FOREIGN KEY("id_usuario") REFERENCES "Usuarios"("id");
ALTER TABLE
    "Recursos" ADD CONSTRAINT "recursos_id_etapa_processo_foreign" FOREIGN KEY("id_etapa_processo") REFERENCES "Etapas Processo"("id");
ALTER TABLE
    "Enderecos" ADD CONSTRAINT "enderecos_id_usuario_foreign" FOREIGN KEY("id_usuario") REFERENCES "Usuarios"("id");
ALTER TABLE
    "Recursos" ADD CONSTRAINT "recursos_id_gestor_foreign" FOREIGN KEY("id_gestor") REFERENCES "Gestores"("id");
ALTER TABLE
    "Candidaturas" ADD CONSTRAINT "candidaturas_id_curso_foreign" FOREIGN KEY("id_curso") REFERENCES "Cursos"("id");
ALTER TABLE
    "Etapas Processo" ADD CONSTRAINT "etapas processo_id_candidatura_foreign" FOREIGN KEY("id_candidatura") REFERENCES "Candidaturas"("id");
ALTER TABLE
    "Etapas Processo" ADD CONSTRAINT "etapas processo_id_gestor_foreign" FOREIGN KEY("id_gestor") REFERENCES "Gestores"("id");
ALTER TABLE
    "Gestores" ADD CONSTRAINT "gestores_id_usuario_foreign" FOREIGN KEY("id_usuario") REFERENCES "Usuarios"("id");